eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    com.tudominio: DEBUG